const express = require("express");
const AdmZip = require("adm-zip");

const router = express.Router();

router.post("/", (req, res) => {
  try {
    const web_arr = Array.isArray(req.body.web_arr)
      ? req.body.web_arr
      : [];

    if (web_arr.length === 0) {
      return res.status(400).json({
        message: "Please select at least one website."
      });
    }

    /*
      Remove unwanted characters and make all values lowercase.
    */
    const websites = web_arr
      .map((site) => String(site).trim().toLowerCase())
      .filter(Boolean);

    /*
      Convert:

      youtube
      instagram
      netflix

      into:

      *://*.youtube.com/*
      *://youtube.com/*
      *://*.instagram.com/*
      etc.
    */

    const rules = websites.map((site, index) => ({
      id: index + 1,
      priority: 1,
      action: {
        type: "block"
      },
      condition: {
        urlFilter: `||${site}.com`,
        resourceTypes: ["main_frame"]
      }
    }));

    /*
      Manifest V3
    */
    const manifest = {
      manifest_version: 3,

      name: "Refrain Website Blocker",

      version: "1.0.0",

      description:
        "Website blocker generated by the Refrain Addiction application.",

      permissions: [
        "declarativeNetRequest"
      ],

      host_permissions: [
        "*://*/*"
      ],

      background: {
        service_worker: "background.js"
      },

      declarative_net_request: {
        rule_resources: [
          {
            id: "blocking_rules",
            enabled: true,
            path: "rules.json"
          }
        ]
      }
    };

    /*
      Rules file
    */
    const rulesJson = JSON.stringify(rules, null, 2);

    /*
      Background service worker.
      No extra functionality is required here.
    */
    const backgroundJs = `
// Refrain Website Blocker

console.log("Refrain Website Blocker is active.");
`;

    /*
      Create ZIP
    */
    const zip = new AdmZip();

    zip.addFile(
      "manifest.json",
      Buffer.from(JSON.stringify(manifest, null, 2), "utf8")
    );

    zip.addFile(
      "rules.json",
      Buffer.from(rulesJson, "utf8")
    );

    zip.addFile(
      "background.js",
      Buffer.from(backgroundJs, "utf8")
    );

    /*
      Generate ZIP buffer
    */
    const zipBuffer = zip.toBuffer();

    /*
      Send ZIP directly to browser
    */
    res.setHeader(
      "Content-Type",
      "application/zip"
    );

    res.setHeader(
      "Content-Disposition",
      'attachment; filename="refrain-website-blocker.zip"'
    );

    res.setHeader(
      "Content-Length",
      zipBuffer.length
    );

    res.send(zipBuffer);

  } catch (error) {

    console.error(
      "Website blocker error:",
      error
    );

    res.status(500).json({
      message: "Failed to create website blocker.",
      error: error.message
    });

  }
});

module.exports = router;